name: Auto-label Issues

on:
  issues:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Add component and status labels
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body || '';
            const title = issue.title || '';
            
            // Parse component from issue body
            const componentMatch = body.match(/###\s*📂 Affected Component\s*\n\s*(.+)/i) ||
                                   body.match(/###\s*🔧 (?:WTM|Infeed) Component\s*\n\s*(.+)/i);
            
            if (componentMatch) {
              const component = componentMatch[1].trim().toLowerCase()
                .replace(/\s+/g, '-')
                .replace(/\//g, '-')
                .replace(/[()]/g, '');
              
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: [`component:${component}`]
              });
            }
            
            // Parse priority
            const priorityMatch = body.match(/###\s*🚨 Priority\s*\n\s*(P[0-3])/i);
            if (priorityMatch) {
              const priority = priorityMatch[1].toLowerCase();
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: [priority]
              });
            }
            
            // Parse bot operational status for robot issues
            const botStatusMatch = body.match(/###\s*🚦 Bot Operational Status\s*\n\s*(.+)/i);
            if (botStatusMatch) {
              const status = botStatusMatch[1].trim().toLowerCase();
              if (status.includes('down')) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ['bot-down']
                });
              } else if (status.includes('degraded')) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ['bot-degraded']
                });
              }
            }
            
            console.log('Auto-labeling completed');
